# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  jobsearchserver:
    image: jobsearchserver
    build:
      context: .
      dockerfile: jobsearch-server/Dockerfile
    ports:
      - 1233:1233
      - 1234:1234
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
